# Generated by Django 3.2.6 on 2022-03-19 06:44

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=100)),
                ('logo', models.FileField(default='null', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('officer_name', models.CharField(max_length=100)),
                ('officer_position', models.CharField(max_length=100)),
                ('officer_photo', models.FileField(default='null', upload_to='')),
                ('officer_email', models.EmailField(max_length=254)),
                ('office_description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('tags', models.ManyToManyField(to='coa.ServiceTag')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=100)),
                ('advocacy', models.TextField(default=None, max_length=1000)),
                ('core_competencies', models.TextField(default=None, max_length=1000)),
                ('project1_name', models.CharField(default=None, max_length=100)),
                ('project1_description', models.TextField(default=None, max_length=1000)),
                ('project1_photo', models.FileField(default='null', upload_to='')),
                ('project2_name', models.CharField(default=None, max_length=100)),
                ('project2_description', models.TextField(default=None, max_length=1000)),
                ('project2_photo', models.FileField(default='null', upload_to='')),
                ('project3_name', models.CharField(default=None, max_length=100)),
                ('project3_description', models.TextField(default=None, max_length=1000)),
                ('project3_photo', models.FileField(default='null', upload_to='')),
                ('memberstory1_name', models.CharField(default=None, max_length=100)),
                ('memberstory1_content', models.TextField(default=None, max_length=1000)),
                ('memberstory1_photo', models.FileField(default='null', upload_to='')),
                ('memberstory2_name', models.CharField(default=None, max_length=100)),
                ('memberstory2_content', models.TextField(default=None, max_length=1000)),
                ('memberstory2_photo', models.FileField(default='null', upload_to='')),
                ('cluster', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='coa.cluster')),
                ('tags', models.ManyToManyField(to='coa.OrganizationTag')),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('date', models.DateField(default=None)),
                ('photo', models.FileField(default='null', upload_to='')),
                ('photoCaption', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('categories', models.ManyToManyField(to='coa.NewsletterCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('event_link', models.URLField(default=None)),
                ('start_date', models.DateField(default=None)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('start_time', models.TimeField(blank=True, default=None, null=True)),
                ('end_time', models.TimeField(blank=True, default=None, null=True)),
                ('all_day', models.BooleanField(blank=True, default=False)),
                ('organization', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='coa.organization')),
            ],
        ),
    ]
