# Generated by Django 3.2.6 on 2022-03-10 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='cluster',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='coa.cluster'),
        ),
    ]
