# Generated by Django 3.2.6 on 2022-03-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0002_organization_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=None),
        ),
    ]
