# Generated by Django 3.2.6 on 2022-03-10 13:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0004_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='office_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
