# Generated by Django 3.2.6 on 2022-03-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0006_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='newsletter',
            name='tags',
            field=models.ManyToManyField(to='coa.NewsletterTag'),
        ),
    ]
