# Generated by Django 3.2.6 on 2022-03-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0007_auto_20220310_2146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsletterTag',
            new_name='NewsletterCategory',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='tags',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='categories',
            field=models.ManyToManyField(to='coa.NewsletterCategory'),
        ),
    ]
