# Generated by Django 3.2.6 on 2022-03-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0008_auto_20220310_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='all_day',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_link',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='advocacy',
            field=models.TextField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='organization',
            name='core_competencies',
            field=models.TextField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='organization',
            name='memberstory1_content',
            field=models.TextField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='organization',
            name='memberstory1_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='memberstory1_photo',
            field=models.FileField(default='null', upload_to=''),
        ),
        migrations.AddField(
            model_name='organization',
            name='memberstory2_content',
            field=models.TextField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='organization',
            name='memberstory2_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='memberstory2_photo',
            field=models.FileField(default='null', upload_to=''),
        ),
        migrations.AddField(
            model_name='organization',
            name='project1_description',
            field=models.TextField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='organization',
            name='project1_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='project1_photo',
            field=models.FileField(default='null', upload_to=''),
        ),
        migrations.AddField(
            model_name='organization',
            name='project2_description',
            field=models.TextField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='organization',
            name='project2_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='project2_photo',
            field=models.FileField(default='null', upload_to=''),
        ),
        migrations.AddField(
            model_name='organization',
            name='project3_description',
            field=models.TextField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='organization',
            name='project3_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='project3_photo',
            field=models.FileField(default='null', upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=None),
        ),
    ]
