# Generated by Django 3.2.6 on 2022-03-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0009_auto_20220319_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='facebook_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='instagram_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='twitter_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='website_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
