# Generated by Django 3.2.6 on 2022-03-20 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0010_auto_20220320_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='categories',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='coa.newslettercategory'),
        ),
    ]
