# Generated by Django 3.2.6 on 2022-03-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0011_auto_20220320_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.FileField(default='null', upload_to=''),
        ),
    ]
