# Generated by Django 3.2.6 on 2022-03-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0012_auto_20220321_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='description',
            field=models.TextField(default=None, max_length=1000),
        ),
    ]
