# Generated by Django 3.2.6 on 2022-03-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0013_cluster_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='officer_email',
            field=models.EmailField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='officer_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='cluster',
            name='officer_photo',
            field=models.FileField(default='null', upload_to=''),
        ),
        migrations.AlterField(
            model_name='office',
            name='officer_email',
            field=models.EmailField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
