# Generated by Django 3.2.6 on 2022-03-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0014_auto_20220322_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='officer_email',
            field=models.EmailField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='office',
            name='officer_email',
            field=models.EmailField(default=None, max_length=100),
        ),
    ]
