# Generated by Django 3.2.6 on 2022-04-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coa', '0015_auto_20220322_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='link',
            field=models.URLField(default=None),
        ),
    ]
